[tool.black]
line-length = 79

[tool.ruff]
lint.select = ["F401", "I", "UP"]
line-length = 79
target-version = "py310"

[tool.ruff.lint.pyupgrade]
# Preserve types, even if a file imports `from __future__ import annotations`.
keep-runtime-typing = true
